ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "socialFacebook" TEXT NOT NULL DEFAULT '';
ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "socialInstagram" TEXT NOT NULL DEFAULT '';
ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "socialTwitter" TEXT NOT NULL DEFAULT '';
ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "socialWhatsapp" TEXT NOT NULL DEFAULT '';
ALTER TABLE "PlatformConfig" ADD COLUMN IF NOT EXISTS "socialTiktok" TEXT NOT NULL DEFAULT '';
